name: Build, Push Docker Image and Deploy on Windows

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version
        id: extract_version
        run: |
          VERSION=$(date +%Y%m%d%H%M%S)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/spoter-be:${{ env.VERSION }} -t ${{ secrets.DOCKER_USERNAME }}/spoter-be:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/spoter-be:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/spoter-be:latest

      - name: SSH into Windows server and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
       
            powershell -Command "
              if (-not (Get-Process 'com.docker.proxy' -ErrorAction SilentlyContinue)) {
                Write-Output 'Docker Desktop is not running. Please start Docker Desktop.'
                exit 1
              }

              docker pull ${{ secrets.DOCKER_USERNAME }}/spoter-be:${{ env.VERSION }}
              Write-Output 'Docker pull completed'

              docker stop spoter-be 2>$null
              docker rm spoter-be 2>$null
              Write-Output 'Stopped and removed old container'

              Write-Output 'Starting docker run...'
              docker run -d --name spoter-be --env-file 'H:\spoter_data\.env' -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/spoter-be:${{ env.VERSION }}
              if ($LASTEXITCODE -ne 0) {
                Write-Output 'Failed to start container'
                docker logs spoter-be
                exit 1
              }
              Write-Output 'Docker container started'

              Start-Sleep -Seconds 10

              $status = docker inspect -f '{{.State.Running}}' spoter-be
              if ($status -ne 'true') {
                Write-Output 'Container is not running!'
                docker logs spoter-be
                exit 1
              }

              docker image prune -a -f
              Write-Output 'Pruned unused images'

              docker ps -a
              docker logs spoter-be --tail 100
            "
